do not require workspace for upgrade operation.

diff --git a/tt b/tt
--- a/tt
+++ b/tt
@@ -39,14 +39,21 @@ main() {
 		>&2 echo
 	fi
 
-	if [[ -z "$(get_workspace_dir)" && ! -z "$1" && "$1" != "workspace" && "$1" != "install" ]]; then
-		>&2 echo "ERROR: You don't have an active workspace. Run 'tt workspace use <workspace>' to select one."
-		>&2 echo
-		>&2 echo Available workspaces:
-		for dep in $(ws_ls); do
-			>&2 echo "  $dep"
-		done
-		return 1
+	if [[ -z "$(get_workspace_dir)" && ! -z "$1" ]]; then
+		case "$1" in
+		install) ;;
+		upgrade) ;;
+		workspace) ;;
+		*)
+			>&2 echo "ERROR: You don't have an active workspace. Run 'tt workspace use <workspace>' to select one."
+			>&2 echo
+			>&2 echo Available workspaces:
+			for dep in $(ws_ls); do
+				>&2 echo "  $dep"
+			done
+			return 1
+			;;
+		esac
 	fi
 
 	run_sub_command tt $@
